DROP DATABASE IF EXISTS Ej;
CREATE DATABASE Ej;
USE Ej;



CREATE TABLE JUGADOR (
	ID INT NOT NULL,
	USERNAME VARCHAR(10) NOT NULL,
	PASS VARCHAR(12),
	EMAIL VARCHAR(30),
	AMIGOS VARCHAR(100),
	PRIMARY KEY(ID)
)ENGINE = InnoDB;


CREATE TABLE PARTIDA (
	ID INT NOT NULL,
	FECHA INT,
	DURACION INT,
	IDGANADOR INT,
	FOREIGN KEY (IDGANADOR) REFERENCES JUGADOR(ID),
	PRIMARY KEY(ID)
)ENGINE = InnoDB;


CREATE TABLE RANKING (
	ID_J INT,
	ID_P INT,
 	PUNTOS INT,
	FOREIGN KEY (ID_J) REFERENCES JUGADOR(ID),
	FOREIGN KEY (ID_P) REFERENCES PARTIDA(ID)
)ENGINE = InnoDB;

INSERT INTO JUGADOR VALUES (1, 'A' , '123', 'A@gmail.com', '2,3');
INSERT INTO JUGADOR VALUES (2, 'B' , '456', 'B@gmail.com', '1,3');
INSERT INTO JUGADOR VALUES (3, 'C' , '789', 'C@gmail.com', '1,3,4');
INSERT INTO JUGADOR VALUES (4, 'D' , '123', 'A@gmail.com', '3');

SELECT * FROM JUGADOR;


/*
UPDATE JUGADOR
SET PASS = REPLACE(PASS, PASS, '000')
WHERE JUGADOR.ID = '1';

UPDATE JUGADOR
SET USERNAME = REPLACE(USERNAME, USERNAME, 'Z')
WHERE JUGADOR.ID = '1';

UPDATE JUGADOR
SET EMAIL = REPLACE(EMAIL, EMAIL, 'Z@gmail.com')
WHERE JUGADOR.ID = '1';

SELECT * FROM JUGADOR;
/*












